# Generated by Django 3.1.7 on 2021-05-01 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='project')),
                ('description', models.TextField()),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
